import { formatCurrencyByLanguage, formatNumberByLanguage } from '../../../constants/i18n';
import type { LanguageCode } from '../../../types';
import type { ConvertCopy } from '../../types/convert';

const COPY: Record<LanguageCode, ConvertCopy> = {
  en: {
    language: 'en',
    headerTitle: 'Convert',
    headerBody: 'Exchange assets instantly',
    fromLabel: 'From',
    toLabel: 'To',
    sourceBalance: 'Available balance',
    estimatedBalance: 'Estimated balance',
    maxLabel: 'Max',
    amountPlaceholder: 'Enter amount',
    destinationPlaceholder: 'Estimated amount',
    quoteTitle: 'Conversion details',
    rateLabel: 'Rate',
    estimatedPriceLabel: 'Estimated price',
    feeLabel: 'Fee',
    spreadLabel: 'Spread',
    providerLabel: 'Provider',
    etaLabel: 'Estimated time',
    regionLabel: 'Availability',
    minimumLabel: 'Minimum',
    emptyStateTitle: 'Choose two assets to start',
    emptyStateBody: 'Select a source asset, enter an amount and review the live estimate before confirming.',
    loadingQuote: 'Updating estimate',
    noPairTitle: 'This conversion is not available',
    noPairBody: 'Review the selected pair or choose another destination asset.',
    unavailableRegion: 'Not available in your region',
    unavailableGeneric: 'This pair is not available right now.',
    askAstra: 'Ask Astra',
    previewLabel: 'Preview conversion',
    convertNow: 'Convert now',
    continueWithProvider: 'Continue with provider',
    recentTitle: 'Recent conversions',
    favoritesTitle: 'Favorites',
    frequentTitle: 'Frequent assets',
    successTitle: 'Conversion completed',
    successBody: 'Your balances were updated with the latest confirmed estimate.',
    walletCta: 'View wallet',
    historyCta: 'View history',
    confirmTitle: 'Confirm conversion',
    confirmBody: 'Review the final estimate before continuing.',
    confirmAction: 'Confirm conversion',
    cancelAction: 'Cancel',
    selectorTitleSource: 'Choose source asset',
    selectorTitleTarget: 'Choose destination asset',
    searchPlaceholder: 'Search asset',
    unavailableTag: 'Unavailable',
    availableByRegionTag: 'Available by region',
    providerManagedTag: 'External provider',
    providerManagedBody: 'Fiat conversion is processed by an external regulated provider.',
    instantBody: 'Crypto to crypto conversion is estimated instantly inside OrbitX.',
    notEnoughBalance: 'You do not have enough balance for this conversion.',
    sameAsset: 'Choose two different assets.',
    sourceRequired: 'Select the source asset first.',
    amountRequired: 'Enter an amount to continue.',
    unsupportedSourceFiat: 'Fiat cannot be used as the source asset in this screen.',
    swapOnlyCrypto: 'Swap is only available when both selected assets are crypto.',
    retakeGuide: 'Resume guide',
  },
  es: {
    language: 'es',
    headerTitle: 'Convertir',
    headerBody: 'Intercambia activos al instante',
    fromLabel: 'Desde',
    toLabel: 'Hacia',
    sourceBalance: 'Saldo disponible',
    estimatedBalance: 'Saldo estimado',
    maxLabel: 'Max',
    amountPlaceholder: 'Ingresa monto',
    destinationPlaceholder: 'Monto estimado',
    quoteTitle: 'Detalles de conversion',
    rateLabel: 'Tasa',
    estimatedPriceLabel: 'Precio estimado',
    feeLabel: 'Comision',
    spreadLabel: 'Spread',
    providerLabel: 'Proveedor',
    etaLabel: 'Tiempo estimado',
    regionLabel: 'Disponibilidad',
    minimumLabel: 'Minimo',
    emptyStateTitle: 'Elige dos activos para comenzar',
    emptyStateBody: 'Selecciona un activo origen, ingresa un monto y revisa el estimado antes de confirmar.',
    loadingQuote: 'Actualizando estimado',
    noPairTitle: 'Esta conversion no esta disponible',
    noPairBody: 'Revisa el par elegido o selecciona otro activo destino.',
    unavailableRegion: 'No disponible en tu region',
    unavailableGeneric: 'Este par no esta disponible por ahora.',
    askAstra: 'Preguntar a Astra',
    previewLabel: 'Previsualizar conversion',
    convertNow: 'Convertir ahora',
    continueWithProvider: 'Continuar con proveedor',
    recentTitle: 'Conversiones recientes',
    favoritesTitle: 'Favoritos',
    frequentTitle: 'Activos frecuentes',
    successTitle: 'Conversion completada',
    successBody: 'Tus balances se actualizaron con el ultimo estimado confirmado.',
    walletCta: 'Ver billetera',
    historyCta: 'Ver historial',
    confirmTitle: 'Confirmar conversion',
    confirmBody: 'Revisa el estimado final antes de continuar.',
    confirmAction: 'Confirmar conversion',
    cancelAction: 'Cancelar',
    selectorTitleSource: 'Elegir activo origen',
    selectorTitleTarget: 'Elegir activo destino',
    searchPlaceholder: 'Buscar activo',
    unavailableTag: 'No disponible',
    availableByRegionTag: 'Disponible segun tu region',
    providerManagedTag: 'Proveedor externo',
    providerManagedBody: 'La conversion a fiat se procesa con un proveedor externo regulado.',
    instantBody: 'La conversion crypto a crypto se estima al instante dentro de OrbitX.',
    notEnoughBalance: 'No tienes saldo suficiente para esta conversion.',
    sameAsset: 'Elige dos activos diferentes.',
    sourceRequired: 'Selecciona primero el activo origen.',
    amountRequired: 'Ingresa un monto para continuar.',
    unsupportedSourceFiat: 'En esta pantalla no puedes usar fiat como activo origen.',
    swapOnlyCrypto: 'El intercambio rapido solo esta disponible cuando ambos activos son crypto.',
    retakeGuide: 'Retomar guia',
  },
  pt: {
    language: 'pt',
    headerTitle: 'Converter',
    headerBody: 'Troque ativos instantaneamente',
    fromLabel: 'De',
    toLabel: 'Para',
    sourceBalance: 'Saldo disponivel',
    estimatedBalance: 'Saldo estimado',
    maxLabel: 'Max',
    amountPlaceholder: 'Insira o valor',
    destinationPlaceholder: 'Valor estimado',
    quoteTitle: 'Detalhes da conversao',
    rateLabel: 'Taxa',
    estimatedPriceLabel: 'Preco estimado',
    feeLabel: 'Taxa',
    spreadLabel: 'Spread',
    providerLabel: 'Provedor',
    etaLabel: 'Tempo estimado',
    regionLabel: 'Disponibilidade',
    minimumLabel: 'Minimo',
    emptyStateTitle: 'Escolha dois ativos para comecar',
    emptyStateBody: 'Selecione o ativo de origem, informe o valor e revise a estimativa antes de confirmar.',
    loadingQuote: 'Atualizando estimativa',
    noPairTitle: 'Esta conversao nao esta disponivel',
    noPairBody: 'Revise o par selecionado ou escolha outro ativo de destino.',
    unavailableRegion: 'Indisponivel na sua regiao',
    unavailableGeneric: 'Este par nao esta disponivel agora.',
    askAstra: 'Perguntar para Astra',
    previewLabel: 'Prever conversao',
    convertNow: 'Converter agora',
    continueWithProvider: 'Continuar com o provedor',
    recentTitle: 'Conversoes recentes',
    favoritesTitle: 'Favoritos',
    frequentTitle: 'Ativos frequentes',
    successTitle: 'Conversao concluida',
    successBody: 'Seus saldos foram atualizados com a ultima estimativa confirmada.',
    walletCta: 'Ver carteira',
    historyCta: 'Ver historico',
    confirmTitle: 'Confirmar conversao',
    confirmBody: 'Revise a estimativa final antes de continuar.',
    confirmAction: 'Confirmar conversao',
    cancelAction: 'Cancelar',
    selectorTitleSource: 'Escolher ativo de origem',
    selectorTitleTarget: 'Escolher ativo de destino',
    searchPlaceholder: 'Buscar ativo',
    unavailableTag: 'Indisponivel',
    availableByRegionTag: 'Disponivel conforme a regiao',
    providerManagedTag: 'Provedor externo',
    providerManagedBody: 'A conversao para fiat e processada por um provedor externo regulado.',
    instantBody: 'A conversao cripto para cripto e estimada instantaneamente dentro da OrbitX.',
    notEnoughBalance: 'Voce nao tem saldo suficiente para esta conversao.',
    sameAsset: 'Escolha dois ativos diferentes.',
    sourceRequired: 'Selecione primeiro o ativo de origem.',
    amountRequired: 'Insira um valor para continuar.',
    unsupportedSourceFiat: 'Nesta tela, fiat nao pode ser o ativo de origem.',
    swapOnlyCrypto: 'A inversao rapida so esta disponivel quando ambos os ativos sao cripto.',
    retakeGuide: 'Retomar guia',
  },
  'zh-Hans': {
    language: 'zh-Hans',
    headerTitle: '兑换',
    headerBody: '即时交换资产',
    fromLabel: '从',
    toLabel: '到',
    sourceBalance: '可用余额',
    estimatedBalance: '预计余额',
    maxLabel: '最大',
    amountPlaceholder: '输入金额',
    destinationPlaceholder: '预计到账',
    quoteTitle: '兑换详情',
    rateLabel: '汇率',
    estimatedPriceLabel: '预计价格',
    feeLabel: '费用',
    spreadLabel: '价差',
    providerLabel: '提供方',
    etaLabel: '预计时间',
    regionLabel: '可用性',
    minimumLabel: '最低金额',
    emptyStateTitle: '先选择两个资产',
    emptyStateBody: '选择来源资产、输入金额，然后在确认前查看最新估算。',
    loadingQuote: '正在更新估算',
    noPairTitle: '该兑换当前不可用',
    noPairBody: '请检查所选交易对或改选其他目标资产。',
    unavailableRegion: '你的地区不可用',
    unavailableGeneric: '该交易对当前不可用。',
    askAstra: '询问 Astra',
    previewLabel: '预览兑换',
    convertNow: '立即兑换',
    continueWithProvider: '继续到提供方',
    recentTitle: '最近兑换',
    favoritesTitle: '收藏',
    frequentTitle: '常用资产',
    successTitle: '兑换完成',
    successBody: '你的余额已按最新确认估算更新。',
    walletCta: '查看钱包',
    historyCta: '查看历史',
    confirmTitle: '确认兑换',
    confirmBody: '继续前请核对最终估算。',
    confirmAction: '确认兑换',
    cancelAction: '取消',
    selectorTitleSource: '选择来源资产',
    selectorTitleTarget: '选择目标资产',
    searchPlaceholder: '搜索资产',
    unavailableTag: '不可用',
    availableByRegionTag: '因地区而定',
    providerManagedTag: '外部提供方',
    providerManagedBody: '法币兑换由受监管的外部提供方处理。',
    instantBody: '加密货币之间的兑换会在 OrbitX 内即时估算。',
    notEnoughBalance: '余额不足，无法完成兑换。',
    sameAsset: '请选择两个不同的资产。',
    sourceRequired: '请先选择来源资产。',
    amountRequired: '请输入金额后继续。',
    unsupportedSourceFiat: '此页面暂不支持用法币作为来源资产。',
    swapOnlyCrypto: '只有当两个资产都是加密货币时才可快速互换。',
    retakeGuide: '继续指南',
  },
  hi: {
    language: 'hi',
    headerTitle: 'कन्वर्ट',
    headerBody: 'एसेट तुरंत बदलें',
    fromLabel: 'से',
    toLabel: 'में',
    sourceBalance: 'उपलब्ध बैलेंस',
    estimatedBalance: 'अनुमानित बैलेंस',
    maxLabel: 'मैक्स',
    amountPlaceholder: 'राशि दर्ज करें',
    destinationPlaceholder: 'अनुमानित राशि',
    quoteTitle: 'कन्वर्जन विवरण',
    rateLabel: 'रेट',
    estimatedPriceLabel: 'अनुमानित कीमत',
    feeLabel: 'फीस',
    spreadLabel: 'स्प्रेड',
    providerLabel: 'प्रदाता',
    etaLabel: 'अनुमानित समय',
    regionLabel: 'उपलब्धता',
    minimumLabel: 'न्यूनतम',
    emptyStateTitle: 'शुरू करने के लिए दो एसेट चुनें',
    emptyStateBody: 'सोर्स एसेट चुनें, राशि दर्ज करें और पुष्टि से पहले अनुमान देखें।',
    loadingQuote: 'अनुमान अपडेट हो रहा है',
    noPairTitle: 'यह कन्वर्जन उपलब्ध नहीं है',
    noPairBody: 'चुने हुए पेयर को जांचें या दूसरा डेस्टिनेशन एसेट चुनें।',
    unavailableRegion: 'आपके क्षेत्र में उपलब्ध नहीं',
    unavailableGeneric: 'यह पेयर अभी उपलब्ध नहीं है।',
    askAstra: 'Astra से पूछें',
    previewLabel: 'कन्वर्जन प्रीव्यू',
    convertNow: 'अभी कन्वर्ट करें',
    continueWithProvider: 'प्रदाता के साथ जारी रखें',
    recentTitle: 'हाल की कन्वर्जन',
    favoritesTitle: 'फेवरेट',
    frequentTitle: 'अक्सर उपयोग किए जाने वाले एसेट',
    successTitle: 'कन्वर्जन पूरा हुआ',
    successBody: 'आपके बैलेंस को अंतिम पुष्टि किए गए अनुमान से अपडेट कर दिया गया है।',
    walletCta: 'वॉलेट देखें',
    historyCta: 'इतिहास देखें',
    confirmTitle: 'कन्वर्जन की पुष्टि करें',
    confirmBody: 'जारी रखने से पहले अंतिम अनुमान देखें।',
    confirmAction: 'कन्वर्जन की पुष्टि करें',
    cancelAction: 'रद्द करें',
    selectorTitleSource: 'सोर्स एसेट चुनें',
    selectorTitleTarget: 'डेस्टिनेशन एसेट चुनें',
    searchPlaceholder: 'एसेट खोजें',
    unavailableTag: 'उपलब्ध नहीं',
    availableByRegionTag: 'क्षेत्र के अनुसार उपलब्ध',
    providerManagedTag: 'बाहरी प्रदाता',
    providerManagedBody: 'फिएट कन्वर्जन एक बाहरी रेगुलेटेड प्रदाता द्वारा प्रोसेस होता है।',
    instantBody: 'क्रिप्टो से क्रिप्टो कन्वर्जन OrbitX के भीतर तुरंत अनुमानित होता है।',
    notEnoughBalance: 'इस कन्वर्जन के लिए पर्याप्त बैलेंस नहीं है।',
    sameAsset: 'दो अलग एसेट चुनें।',
    sourceRequired: 'पहले सोर्स एसेट चुनें।',
    amountRequired: 'जारी रखने के लिए राशि दर्ज करें।',
    unsupportedSourceFiat: 'इस स्क्रीन में फिएट को सोर्स एसेट के रूप में उपयोग नहीं किया जा सकता।',
    swapOnlyCrypto: 'त्वरित स्वैप केवल तब उपलब्ध है जब दोनों एसेट क्रिप्टो हों।',
    retakeGuide: 'गाइड जारी रखें',
  },
  ru: {
    language: 'ru',
    headerTitle: 'Конвертировать',
    headerBody: 'Мгновенный обмен активов',
    fromLabel: 'Из',
    toLabel: 'В',
    sourceBalance: 'Доступный баланс',
    estimatedBalance: 'Оценочный баланс',
    maxLabel: 'Макс',
    amountPlaceholder: 'Введите сумму',
    destinationPlaceholder: 'Оценочная сумма',
    quoteTitle: 'Детали конвертации',
    rateLabel: 'Курс',
    estimatedPriceLabel: 'Оценочная цена',
    feeLabel: 'Комиссия',
    spreadLabel: 'Спред',
    providerLabel: 'Провайдер',
    etaLabel: 'Оценочное время',
    regionLabel: 'Доступность',
    minimumLabel: 'Минимум',
    emptyStateTitle: 'Выберите два актива',
    emptyStateBody: 'Выберите исходный актив, введите сумму и проверьте оценку перед подтверждением.',
    loadingQuote: 'Обновляем оценку',
    noPairTitle: 'Эта конвертация недоступна',
    noPairBody: 'Проверьте выбранную пару или выберите другой актив назначения.',
    unavailableRegion: 'Недоступно в вашем регионе',
    unavailableGeneric: 'Эта пара сейчас недоступна.',
    askAstra: 'Спросить Astra',
    previewLabel: 'Предпросмотр конвертации',
    convertNow: 'Конвертировать сейчас',
    continueWithProvider: 'Продолжить у провайдера',
    recentTitle: 'Последние конвертации',
    favoritesTitle: 'Избранное',
    frequentTitle: 'Частые активы',
    successTitle: 'Конвертация завершена',
    successBody: 'Ваши балансы обновлены по последней подтвержденной оценке.',
    walletCta: 'Открыть кошелек',
    historyCta: 'Открыть историю',
    confirmTitle: 'Подтвердить конвертацию',
    confirmBody: 'Проверьте итоговую оценку перед продолжением.',
    confirmAction: 'Подтвердить конвертацию',
    cancelAction: 'Отмена',
    selectorTitleSource: 'Выберите актив-источник',
    selectorTitleTarget: 'Выберите актив назначения',
    searchPlaceholder: 'Поиск актива',
    unavailableTag: 'Недоступно',
    availableByRegionTag: 'Доступно по региону',
    providerManagedTag: 'Внешний провайдер',
    providerManagedBody: 'Конвертация в фиат выполняется внешним регулируемым провайдером.',
    instantBody: 'Конвертация крипто в крипто оценивается мгновенно внутри OrbitX.',
    notEnoughBalance: 'Недостаточно средств для этой конвертации.',
    sameAsset: 'Выберите два разных актива.',
    sourceRequired: 'Сначала выберите исходный актив.',
    amountRequired: 'Введите сумму, чтобы продолжить.',
    unsupportedSourceFiat: 'На этом экране фиат нельзя использовать как исходный актив.',
    swapOnlyCrypto: 'Быстрый обмен доступен только когда оба актива являются криптовалютами.',
    retakeGuide: 'Продолжить руководство',
  },
  ar: {
    language: 'ar',
    headerTitle: 'تحويل',
    headerBody: 'بدل الأصول فورا',
    fromLabel: 'من',
    toLabel: 'إلى',
    sourceBalance: 'الرصيد المتاح',
    estimatedBalance: 'الرصيد التقديري',
    maxLabel: 'الحد الأقصى',
    amountPlaceholder: 'أدخل المبلغ',
    destinationPlaceholder: 'المبلغ التقديري',
    quoteTitle: 'تفاصيل التحويل',
    rateLabel: 'السعر',
    estimatedPriceLabel: 'السعر التقديري',
    feeLabel: 'الرسوم',
    spreadLabel: 'السبريد',
    providerLabel: 'المزوّد',
    etaLabel: 'الوقت المتوقع',
    regionLabel: 'التوفر',
    minimumLabel: 'الحد الأدنى',
    emptyStateTitle: 'اختر أصلين للبدء',
    emptyStateBody: 'اختر الأصل المصدر وأدخل المبلغ ثم راجع التقدير قبل التأكيد.',
    loadingQuote: 'يتم تحديث التقدير',
    noPairTitle: 'هذا التحويل غير متاح',
    noPairBody: 'راجع الزوج المحدد أو اختر أصلا آخر للوجهة.',
    unavailableRegion: 'غير متاح في منطقتك',
    unavailableGeneric: 'هذا الزوج غير متاح حاليا.',
    askAstra: 'اسأل Astra',
    previewLabel: 'معاينة التحويل',
    convertNow: 'حوّل الآن',
    continueWithProvider: 'تابع مع المزوّد',
    recentTitle: 'أحدث التحويلات',
    favoritesTitle: 'المفضلة',
    frequentTitle: 'الأصول المتكررة',
    successTitle: 'اكتمل التحويل',
    successBody: 'تم تحديث أرصدتك بناء على آخر تقدير مؤكّد.',
    walletCta: 'عرض المحفظة',
    historyCta: 'عرض السجل',
    confirmTitle: 'تأكيد التحويل',
    confirmBody: 'راجع التقدير النهائي قبل المتابعة.',
    confirmAction: 'تأكيد التحويل',
    cancelAction: 'إلغاء',
    selectorTitleSource: 'اختر الأصل المصدر',
    selectorTitleTarget: 'اختر الأصل الوجهة',
    searchPlaceholder: 'ابحث عن أصل',
    unavailableTag: 'غير متاح',
    availableByRegionTag: 'متاح حسب المنطقة',
    providerManagedTag: 'مزوّد خارجي',
    providerManagedBody: 'التحويل إلى العملات الورقية تتم معالجته عبر مزوّد خارجي منظم.',
    instantBody: 'يتم تقدير تحويل العملات المشفرة داخل OrbitX بشكل فوري.',
    notEnoughBalance: 'ليس لديك رصيد كاف لهذا التحويل.',
    sameAsset: 'اختر أصلين مختلفين.',
    sourceRequired: 'اختر الأصل المصدر أولا.',
    amountRequired: 'أدخل مبلغا للمتابعة.',
    unsupportedSourceFiat: 'لا يمكن استخدام العملة الورقية كأصل مصدر في هذه الشاشة.',
    swapOnlyCrypto: 'عكس الأصول متاح فقط عندما يكون الأصلان من العملات المشفرة.',
    retakeGuide: 'استئناف الدليل',
  },
  id: {
    language: 'id',
    headerTitle: 'Konversi',
    headerBody: 'Tukar aset secara instan',
    fromLabel: 'Dari',
    toLabel: 'Ke',
    sourceBalance: 'Saldo tersedia',
    estimatedBalance: 'Saldo estimasi',
    maxLabel: 'Maks',
    amountPlaceholder: 'Masukkan jumlah',
    destinationPlaceholder: 'Jumlah estimasi',
    quoteTitle: 'Detail konversi',
    rateLabel: 'Kurs',
    estimatedPriceLabel: 'Harga estimasi',
    feeLabel: 'Biaya',
    spreadLabel: 'Spread',
    providerLabel: 'Penyedia',
    etaLabel: 'Estimasi waktu',
    regionLabel: 'Ketersediaan',
    minimumLabel: 'Minimum',
    emptyStateTitle: 'Pilih dua aset untuk mulai',
    emptyStateBody: 'Pilih aset asal, masukkan jumlah, lalu tinjau estimasi sebelum konfirmasi.',
    loadingQuote: 'Memperbarui estimasi',
    noPairTitle: 'Konversi ini tidak tersedia',
    noPairBody: 'Tinjau pasangan yang dipilih atau pilih aset tujuan lain.',
    unavailableRegion: 'Tidak tersedia di wilayahmu',
    unavailableGeneric: 'Pasangan ini belum tersedia sekarang.',
    askAstra: 'Tanya Astra',
    previewLabel: 'Pratinjau konversi',
    convertNow: 'Konversi sekarang',
    continueWithProvider: 'Lanjutkan dengan penyedia',
    recentTitle: 'Konversi terbaru',
    favoritesTitle: 'Favorit',
    frequentTitle: 'Aset yang sering dipakai',
    successTitle: 'Konversi selesai',
    successBody: 'Saldo kamu sudah diperbarui dengan estimasi terakhir yang dikonfirmasi.',
    walletCta: 'Lihat wallet',
    historyCta: 'Lihat riwayat',
    confirmTitle: 'Konfirmasi konversi',
    confirmBody: 'Tinjau estimasi akhir sebelum melanjutkan.',
    confirmAction: 'Konfirmasi konversi',
    cancelAction: 'Batal',
    selectorTitleSource: 'Pilih aset asal',
    selectorTitleTarget: 'Pilih aset tujuan',
    searchPlaceholder: 'Cari aset',
    unavailableTag: 'Tidak tersedia',
    availableByRegionTag: 'Tersedia sesuai wilayah',
    providerManagedTag: 'Penyedia eksternal',
    providerManagedBody: 'Konversi ke fiat diproses oleh penyedia eksternal yang teregulasi.',
    instantBody: 'Konversi crypto ke crypto diestimasi secara instan di dalam OrbitX.',
    notEnoughBalance: 'Saldo kamu tidak cukup untuk konversi ini.',
    sameAsset: 'Pilih dua aset yang berbeda.',
    sourceRequired: 'Pilih aset asal terlebih dahulu.',
    amountRequired: 'Masukkan jumlah untuk melanjutkan.',
    unsupportedSourceFiat: 'Di layar ini fiat tidak bisa dipakai sebagai aset asal.',
    swapOnlyCrypto: 'Tukar balik cepat hanya tersedia saat kedua aset sama-sama crypto.',
    retakeGuide: 'Lanjutkan panduan',
  },
};

export function getConvertCopy(language: LanguageCode): ConvertCopy {
  return COPY[language] ?? COPY.en;
}

export function formatConvertAmount(
  language: LanguageCode,
  value: number,
  symbol?: string,
  maximumFractionDigits = 6,
) {
  if (!Number.isFinite(value)) {
    return '--';
  }

  const formatted = formatNumberByLanguage(language, value, {
    minimumFractionDigits: value >= 100 ? 2 : 0,
    maximumFractionDigits,
  });

  return symbol ? `${formatted} ${symbol}` : formatted;
}

export function formatConvertMoney(language: LanguageCode, value: number, currency = 'USD') {
  return formatCurrencyByLanguage(language, value, currency);
}
