import type { TradingProviderDefinition, TradingProviderId } from '../types/trading';

export const TRADING_PROVIDER_DEFINITIONS: Record<
  TradingProviderId,
  TradingProviderDefinition
> = {
  mock: {
    id: 'mock',
    name: 'Mock Trading',
    displayName: 'Modo demo',
    mode: 'demo',
    supportsSpot: true,
    supportsFutures: false,
    supportsOrderBook: true,
    supportsPositions: false,
    supportsSubAccounts: false,
    supportsInternalTransfers: false,
    supportsWithdrawals: false,
    supportsDeposits: false,
    supportsOAuth: false,
    supportsApiKeys: false,
    supportsRealOrders: false,
    requiresBackendSigning: false,
    isEnabled: true,
    isProductionReady: false,
    requiresKyc: false,
    requiresLegalApproval: false,
    notes: 'Demo local para QA. No ejecuta ordenes ni mueve saldos reales.',
  },
  okx: {
    id: 'okx',
    name: 'OKX Broker',
    displayName: 'Proveedor broker',
    mode: 'broker',
    supportsSpot: true,
    supportsFutures: true,
    supportsOrderBook: true,
    supportsPositions: true,
    supportsSubAccounts: true,
    supportsInternalTransfers: true,
    supportsWithdrawals: false,
    supportsDeposits: true,
    supportsOAuth: false,
    supportsApiKeys: true,
    supportsRealOrders: false,
    requiresBackendSigning: true,
    isEnabled: false,
    isProductionReady: false,
    requiresKyc: true,
    requiresLegalApproval: true,
    notes:
      'Preparado para backend QVEX. Nunca debe firmar ni guardar secretos OKX en frontend.',
  },
  binance: {
    id: 'binance',
    name: 'Binance Broker',
    displayName: 'Proveedor futuro',
    mode: 'broker',
    supportsSpot: true,
    supportsFutures: true,
    supportsOrderBook: true,
    supportsPositions: true,
    supportsSubAccounts: true,
    supportsInternalTransfers: true,
    supportsWithdrawals: false,
    supportsDeposits: true,
    supportsOAuth: false,
    supportsApiKeys: true,
    supportsRealOrders: false,
    requiresBackendSigning: true,
    isEnabled: false,
    isProductionReady: false,
    requiresKyc: true,
    requiresLegalApproval: true,
    notes: 'Proveedor futuro. Requiere contrato broker, backend y aprobacion legal.',
  },
  mexc: {
    id: 'mexc',
    name: 'MEXC Broker',
    displayName: 'Proveedor futuro',
    mode: 'broker',
    supportsSpot: true,
    supportsFutures: true,
    supportsOrderBook: true,
    supportsPositions: true,
    supportsSubAccounts: false,
    supportsInternalTransfers: false,
    supportsWithdrawals: false,
    supportsDeposits: true,
    supportsOAuth: false,
    supportsApiKeys: true,
    supportsRealOrders: false,
    requiresBackendSigning: true,
    isEnabled: false,
    isProductionReady: false,
    requiresKyc: true,
    requiresLegalApproval: true,
    notes: 'Proveedor futuro. No productivo en esta fase.',
  },
  bybit: {
    id: 'bybit',
    name: 'Bybit Broker',
    displayName: 'Proveedor futuro',
    mode: 'broker',
    supportsSpot: true,
    supportsFutures: true,
    supportsOrderBook: true,
    supportsPositions: true,
    supportsSubAccounts: true,
    supportsInternalTransfers: true,
    supportsWithdrawals: false,
    supportsDeposits: true,
    supportsOAuth: false,
    supportsApiKeys: true,
    supportsRealOrders: false,
    requiresBackendSigning: true,
    isEnabled: false,
    isProductionReady: false,
    requiresKyc: true,
    requiresLegalApproval: true,
    notes: 'Proveedor futuro. No productivo en esta fase.',
  },
  orbitx: {
    id: 'orbitx',
    name: 'QVEX Engine',
    displayName: 'Motor propio futuro',
    mode: 'native',
    supportsSpot: false,
    supportsFutures: false,
    supportsOrderBook: false,
    supportsPositions: false,
    supportsSubAccounts: false,
    supportsInternalTransfers: true,
    supportsWithdrawals: false,
    supportsDeposits: false,
    supportsOAuth: false,
    supportsApiKeys: false,
    supportsRealOrders: false,
    requiresBackendSigning: true,
    isEnabled: false,
    isProductionReady: false,
    requiresKyc: true,
    requiresLegalApproval: true,
    notes: 'Placeholder para matching engine propio de QVEX.',
  },
};

export function getTradingProviderDefinition(providerId: TradingProviderId) {
  return TRADING_PROVIDER_DEFINITIONS[providerId];
}

export function getTradingProviderDefinitions() {
  return Object.values(TRADING_PROVIDER_DEFINITIONS);
}
