import { StyleSheet } from 'react-native';

import { FONT, ORBITX_COLORS, withOpacity } from '../../../constants/theme';

export const COLORS = {
  ...ORBITX_COLORS,
  text: ORBITX_COLORS.textPrimary,
  textSecondary: ORBITX_COLORS.textSecondary,
  textMuted: ORBITX_COLORS.textMuted,
};

export const styles = StyleSheet.create({
  absoluteFill: StyleSheet.absoluteFillObject,
  root: { flex: 1, backgroundColor: COLORS.background },
  safeArea: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 4 },
  motionTrailTop: {
    position: 'absolute',
    top: 92,
    right: -18,
    width: 180,
    height: 1,
    backgroundColor: withOpacity(COLORS.purpleSoft, 0.11),
    transform: [{ rotate: '-18deg' }],
  },
  motionTrailBottom: {
    position: 'absolute',
    bottom: 150,
    left: -22,
    width: 170,
    height: 1,
    backgroundColor: withOpacity(COLORS.web3Blue, 0.08),
    transform: [{ rotate: '15deg' }],
  },
  pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  header: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  headerIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.7),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  headerTitleWrap: { flex: 1, minWidth: 0 },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  brandGlyph: {
    width: 22,
    height: 22,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: withOpacity(COLORS.purpleSoft, 0.32),
    backgroundColor: withOpacity(COLORS.purple, 0.1),
  },
  headerTitle: {
    color: COLORS.textPrimary,
    fontFamily: FONT.semibold,
    fontSize: 16,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },
  headerSubtitle: {
    color: COLORS.textSecondary,
    fontFamily: FONT.regular,
    fontSize: 11,
    marginTop: 3,
  },
  profileBadge: {
    width: 36,
    height: 36,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.78),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  urlBar: {
    minHeight: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.76),
    paddingLeft: 16,
    paddingRight: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  urlInput: {
    flex: 1,
    minHeight: 42,
    color: COLORS.textPrimary,
    fontFamily: FONT.medium,
    fontSize: 14,
  },
  goButton: {
    width: 38,
    height: 38,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purple,
  },
  quickContent: {
    gap: 8,
    paddingRight: 8,
    marginBottom: 10,
  },
  quickChip: {
    height: 36,
    minWidth: 110,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.surface, 0.72),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  quickChipActive: {
    borderColor: withOpacity(COLORS.purpleSoft, 0.42),
    backgroundColor: withOpacity(COLORS.purple, 0.12),
  },
  quickText: {
    color: COLORS.textPrimary,
    fontFamily: FONT.semibold,
    fontSize: 11,
    textTransform: 'uppercase',
  },
  stage: { flex: 1, minHeight: 0 },
  stageBrowsing: {
    marginHorizontal: -16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  homeContent: { gap: 12, paddingBottom: 12 },
  walletCard: {
    width: '100%',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.surface, 0.78),
    padding: 14,
    gap: 12,
  },
  walletHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  walletTitle: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 18 },
  walletStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 },
  statusDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: COLORS.textMuted },
  statusDotConnected: { backgroundColor: COLORS.green },
  walletStatus: { color: COLORS.textSecondary, fontFamily: FONT.bold, fontSize: 10, letterSpacing: 1, textTransform: 'uppercase' },
  walletStatusConnected: { color: COLORS.green },
  walletAction: {
    minHeight: 34,
    paddingHorizontal: 13,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: withOpacity(COLORS.purpleSoft, 0.28),
    backgroundColor: withOpacity(COLORS.purple, 0.1),
    alignItems: 'center',
    justifyContent: 'center',
  },
  walletActionText: { color: COLORS.purpleSoft, fontFamily: FONT.semibold, fontSize: 10, textTransform: 'uppercase' },
  walletInfoBox: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.background, 0.42),
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  walletInfoLabel: { color: COLORS.textMuted, fontFamily: FONT.medium, fontSize: 10, textTransform: 'uppercase' },
  walletInfoValue: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 14, marginTop: 5 },
  networkBadge: {
    maxWidth: '48%',
    minHeight: 34,
    paddingHorizontal: 11,
    borderRadius: 13,
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  networkBadgeText: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 12 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 16 },
  sectionAction: { color: COLORS.purpleSoft, fontFamily: FONT.semibold, fontSize: 12 },
  trendingGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  trendingCard: {
    width: '48%',
    minHeight: 96,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.surface, 0.75),
    padding: 12,
  },
  tokenGlyph: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.92),
    marginBottom: 12,
  },
  tokenGlyphText: { color: COLORS.textPrimary, fontFamily: FONT.bold, fontSize: 11 },
  tokenChange: { position: 'absolute', right: 16, top: 28, fontFamily: FONT.bold, fontSize: 12 },
  positive: { color: COLORS.green },
  negative: { color: COLORS.red },
  tokenSymbol: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 15 },
  tokenPrice: { color: COLORS.textSecondary, fontFamily: FONT.regular, fontSize: 12, marginTop: 4 },
  featureCard: {
    width: '100%',
    minHeight: 96,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.surface, 0.78),
    overflow: 'hidden',
    flexDirection: 'row',
  },
  featureArt: {
    width: 96,
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.64),
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureLineOne: {
    position: 'absolute',
    width: 112,
    height: 2,
    borderRadius: 2,
    backgroundColor: withOpacity(COLORS.purpleSoft, 0.22),
    transform: [{ rotate: '-19deg' }],
  },
  featureLineTwo: {
    position: 'absolute',
    width: 88,
    height: 2,
    borderRadius: 2,
    backgroundColor: withOpacity(COLORS.web3Blue, 0.14),
    transform: [{ rotate: '22deg' }],
  },
  featureCopy: { flex: 1, padding: 12, justifyContent: 'center', gap: 5 },
  featureTitle: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 16 },
  featureBody: { color: COLORS.textSecondary, fontFamily: FONT.regular, fontSize: 13, lineHeight: 18 },
  featureMeta: { color: COLORS.textMuted, fontFamily: FONT.medium, fontSize: 11, marginTop: 5 },
  dappList: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.surface, 0.75),
    overflow: 'hidden',
  },
  dappRow: {
    minHeight: 60,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  dappIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.82),
  },
  dappCopy: { flex: 1, minWidth: 0 },
  dappTitle: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 15 },
  dappSubtitle: { color: COLORS.textSecondary, fontFamily: FONT.regular, fontSize: 12, marginTop: 4 },
  recentContent: { gap: 10, paddingRight: 16 },
  recentCard: {
    width: 116,
    minHeight: 88,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.surface, 0.76),
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentIcon: {
    width: 36,
    height: 36,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.purple, 0.12),
    marginBottom: 12,
  },
  recentTitle: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 12, textAlign: 'center' },
  recentHost: { color: COLORS.textMuted, fontFamily: FONT.regular, fontSize: 10, marginTop: 4, textAlign: 'center' },
  webViewCard: {
    flex: 1,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceSoft,
  },
  webViewCardFullscreen: {
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: '#FFFFFF',
  },
  webView: { flex: 1, backgroundColor: '#FFFFFF' },
  dappWarningCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    gap: 14,
    backgroundColor: COLORS.background,
  },
  dappWarningIcon: {
    width: 58,
    height: 58,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.warning, 0.12),
    borderWidth: 1,
    borderColor: withOpacity(COLORS.warning, 0.22),
  },
  dappWarningTitle: {
    color: COLORS.textPrimary,
    fontFamily: FONT.bold,
    fontSize: 20,
    textAlign: 'center',
  },
  dappWarningBody: {
    color: COLORS.textSecondary,
    fontFamily: FONT.medium,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  dappWarningActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  dappWarningButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.surface, 0.72),
  },
  dappWarningButtonPrimary: {
    flex: 1.35,
    minHeight: 44,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purple,
  },
  dappWarningSecondary: {
    color: COLORS.textSecondary,
    fontFamily: FONT.semibold,
    fontSize: 12,
  },
  dappWarningPrimaryText: {
    color: COLORS.textPrimary,
    fontFamily: FONT.bold,
    fontSize: 12,
  },
  loadingCard: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    borderRadius: 16,
    backgroundColor: withOpacity(COLORS.background, 0.92),
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 12,
    gap: 9,
  },
  loadingText: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 12 },
  loadingTrack: { height: 4, borderRadius: 4, backgroundColor: withOpacity(COLORS.purpleSoft, 0.12), overflow: 'hidden' },
  loadingFill: { height: '100%', borderRadius: 4, backgroundColor: COLORS.purpleSoft },
  webFallback: {
    flex: 1,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.surface, 0.72),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
  },
  webFallbackFullscreen: {
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: COLORS.background,
  },
  webFallbackTitle: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 19, textAlign: 'center' },
  webFallbackBody: { color: COLORS.textSecondary, fontFamily: FONT.regular, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  primaryButton: {
    minHeight: 42,
    borderRadius: 16,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purple,
  },
  primaryButtonText: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 13 },
  messageCard: {
    minHeight: 38,
    marginTop: 10,
    borderRadius: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: withOpacity(COLORS.surfaceElevated, 0.86),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  messageText: { flex: 1, color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 12 },
  bottomBar: {
    minHeight: 64,
    marginTop: 8,
    borderTopWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.background, 0.95),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
  },
  bottomItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 4 },
  bottomIconWrap: {
    width: 38,
    height: 34,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomIconWrapActive: { backgroundColor: withOpacity(COLORS.purple, 0.16) },
  bottomLabel: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 10, textTransform: 'uppercase' },
  bottomLabelActive: { color: COLORS.purpleSoft },
  settingsSheet: {
    position: 'absolute',
    left: 16,
    right: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceElevated,
    padding: 14,
    gap: 12,
  },
  settingsTitle: { color: COLORS.textPrimary, fontFamily: FONT.semibold, fontSize: 14 },
  settingsRow: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 10 },
  settingsLabel: { color: COLORS.textPrimary, fontFamily: FONT.medium, fontSize: 13 },
});

