export const ORBIT_BROWSER_LINKS = [
  {
    id: 'coinmarketcap',
    title: 'CoinMarketCap',
    subtitle: 'Market caps, dominancia y ranking global',
    url: 'https://coinmarketcap.com/',
    icon: 'bar-chart-outline',
  },
  {
    id: 'popcoin',
    title: 'Popcoin',
    subtitle: 'Exploracion social de tokens emergentes',
    url: 'https://www.popcoin.co/',
    icon: 'sparkles-outline',
  },
  {
    id: 'dextools',
    title: 'DEXTools',
    subtitle: 'Pairs, hot pairs y discovery de mercado',
    url: 'https://www.dextools.io/app/en',
    icon: 'analytics-outline',
  },
  {
    id: 'dexscreener',
    title: 'Dexscreener',
    subtitle: 'Tracking rapido de pools y volumen onchain',
    url: 'https://dexscreener.com/',
    icon: 'pulse-outline',
  },
  {
    id: 'google',
    title: 'Google',
    subtitle: 'Busqueda rapida para noticias o research',
    url: 'https://www.google.com/',
    icon: 'search-outline',
  },
  {
    id: 'trustwallet',
    title: 'Trust Wallet',
    subtitle: 'Wallet y dApps',
    url: 'https://trustwallet.com/browser-extension',
    icon: 'shield-checkmark-outline',
  },
  {
    id: 'jupiter',
    title: 'Jupiter',
    subtitle: 'Agregador de Solana',
    url: 'https://jup.ag/',
    icon: 'planet-outline',
  },
  {
    id: 'uniswap',
    title: 'Uniswap',
    subtitle: 'Swap descentralizado',
    url: 'https://app.uniswap.org/',
    icon: 'swap-horizontal-outline',
  },
  {
    id: 'opensea',
    title: 'OpenSea',
    subtitle: 'NFT marketplace',
    url: 'https://opensea.io/',
    icon: 'images-outline',
  },
  {
    id: 'solscan',
    title: 'Solscan',
    subtitle: 'Explorer para Solana',
    url: 'https://solscan.io/',
    icon: 'search-outline',
  },
] as const;
