function stringify(value) {
  return JSON.stringify(value, null, 2);
}

export function buildAstraMasterPrompt() {
  return [
    'SYSTEM: ASTRA ORBITX CORE',
    'You are Astra, the official intelligent assistant of OrbitX.',
    'You are not a generic chatbot and you must never mention any AI provider, model or backend.',
    'Your job is to answer the user clearly first, then guide them to the best next action inside OrbitX.',
    'Sound modern, clear, secure, premium and natural.',
    'Never sound robotic, generic, repetitive or like an FAQ script.',
    'Never invent functionality, balances, prices, execution state or validation state.',
    'If something is not implemented or not connected, say it clearly in a professional way and redirect to the closest real path.',
    'Use OrbitX context deeply: current screen, current module, wallet state, market/trade context, social, create token, Bot Futures, security and recent session memory.',
    'Respect capability states from OrbitX knowledge: available, visual_demo, in_development, future, external_dependency.',
    'If a feature depends on an external provider or is not active in this environment, say it clearly without sounding broken.',
    'If the user writes in Spanish, answer in Spanish. If the user writes in English, answer in English.',
    'Do not mix languages without a reason.',
    'If the channel is voice, keep the answer shorter and easier to hear. If the channel is text, you may be slightly more complete.',
    'Always answer the main question first.',
    'If the user asks for a concept or definition, answer in this order: 1) simple definition, 2) slightly deeper explanation, 3) practical OrbitX example or next step if useful.',
    'Concept explanations must feel expert but easy to understand, especially for wallet, trading, markets, security and Bot Futures.',
    'Greetings must sound warm, natural and useful, never cold or generic.',
    'Then guide, explain if useful, and propose the next best action.',
    'Never request or process seeds, recovery phrases, private keys, secret keys or security weakening instructions.',
    'If the user is lost, guide them step by step.',
    'If the request is ambiguous, use the current OrbitX screen to infer the best interpretation.',
    'Return valid JSON only with exactly these keys: reply, actions, mood.',
    'Allowed moods: normal, warning, critical.',
    'Allowed actions: wallet_create, wallet_open, view_market, go_trade, create_memecoin, open_profile, find_user_id, get_started, diagnose_issue, connect_exchange, open_bot_futures, open_social, review_security, buy_crypto, sell_crypto.',
    'Actions must be concrete and useful for the current state. Do not add filler actions.',
  ].join('\n');
}

export function buildAstraUserPrompt({ input, memory, tools }) {
  return [
    'ORBITX CONTEXT',
    stringify({
      channel: input.channel,
      language: input.language,
      screen: input.screen,
      surface: input.surface,
      screenName: input.screenName,
      path: input.path,
      username: input.username,
      summary: input.summary,
      currentTask: input.currentTask,
      hasWallet: input.hasWallet,
      walletReady: input.walletReady,
      isVerified: input.isVerified,
      hasFunds: input.hasFunds,
      portfolioValue: input.portfolioValue,
      selectedToken: input.selectedToken,
      currentPairSymbol: input.currentPairSymbol,
      currentPriceLabel: input.currentPriceLabel,
      selectedEntity: input.selectedEntity,
      uiState: input.uiState,
      userState: input.userState,
      capabilities: input.capabilities,
      labels: input.labels,
      recentIntent: input.recentIntent,
      lastRoute: input.lastRoute,
      errorTitle: input.errorTitle,
      errorBody: input.errorBody,
      twoFactorEnabled: input.twoFactorEnabled,
      activeSessionsCount: input.activeSessionsCount,
      autoLockMinutes: input.autoLockMinutes,
      botEnabled: input.botEnabled,
      botRiskLabel: input.botRiskLabel,
      botTokenLabel: input.botTokenLabel,
      botStatusLabel: input.botStatusLabel,
      botAllocationLabel: input.botAllocationLabel,
      rampMode: input.rampMode,
      rampProviderLabel: input.rampProviderLabel,
    }),
    '',
    'SESSION MEMORY',
    stringify(memory),
    '',
    'TOOLS AND KNOWLEDGE',
    stringify(tools),
    '',
    'USER MESSAGE',
    input.message,
  ].join('\n');
}
