import { StyleSheet } from 'react-native';

import { FONT, ORBITX_COLORS, RADII, withOpacity } from '../../../../constants/theme';

export const COLORS = {
  ...ORBITX_COLORS,
  text: ORBITX_COLORS.textPrimary,
  textSecondary: ORBITX_COLORS.textSecondary,
  textMuted: ORBITX_COLORS.textMuted,
  greenBright: ORBITX_COLORS.green,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  scroll: { flex: 1, backgroundColor: COLORS.background },
  content: { width: '100%', paddingHorizontal: 16, paddingTop: 8, gap: 20 },
  contentSmall: { paddingHorizontal: 14, gap: 18 },
  header: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCopy: { flex: 1, minWidth: 0, gap: 2 },
  headerTitle: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 18, lineHeight: 22 },
  headerSubtitle: {
    color: COLORS.textSecondary,
    fontFamily: FONT.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  hero: {
    width: '100%',
    minHeight: 194,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 22,
    paddingVertical: 20,
    overflow: 'hidden',
  },
  heroGlow: {
    position: 'absolute',
    right: -24,
    top: 58,
    width: 180,
    height: 2,
    borderRadius: 2,
    backgroundColor: withOpacity(COLORS.web3Blue, 0.13),
    transform: [{ rotate: '-18deg' }],
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 24,
  },
  activeBadge: {
    minHeight: 26,
    borderRadius: RADII.pill,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 12,
    backgroundColor: withOpacity(COLORS.green, 0.16),
    borderWidth: 1,
    borderColor: withOpacity(COLORS.green, 0.32),
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.greenBright,
  },
  activeBadgeText: {
    color: COLORS.greenBright,
    fontFamily: FONT.bold,
    fontSize: 11,
    letterSpacing: 0.4,
  },
  networkPill: {
    minHeight: 28,
    maxWidth: '45%',
    borderRadius: RADII.pill,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 12,
    backgroundColor: withOpacity('#FFFFFF', 0.06),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  networkDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: COLORS.web3Blue },
  networkPillText: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 12 },
  heroLabel: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 17, lineHeight: 22 },
  heroValue: {
    color: COLORS.text,
    fontFamily: FONT.bold,
    fontSize: 34,
    lineHeight: 42,
    letterSpacing: -0.8,
    marginTop: 4,
  },
  addressPill: {
    alignSelf: 'flex-start',
    minHeight: 32,
    maxWidth: '72%',
    borderRadius: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    paddingHorizontal: 12,
    backgroundColor: withOpacity('#FFFFFF', 0.06),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  addressText: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 12 },
  quickActions: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  quickAction: { flex: 1, alignItems: 'center', gap: 9, minWidth: 0 },
  quickIcon: {
    width: 50,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  quickLabel: { color: COLORS.textSecondary, fontFamily: FONT.semibold, fontSize: 13 },
  infoBanner: {
    width: '100%',
    minHeight: 42,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: withOpacity(COLORS.web3Blue, 0.08),
    borderWidth: 1,
    borderColor: withOpacity(COLORS.web3Blue, 0.16),
  },
  infoBannerError: {
    backgroundColor: withOpacity(COLORS.warning, 0.08),
    borderColor: withOpacity(COLORS.warning, 0.2),
  },
  infoText: {
    flex: 1,
    color: COLORS.textSecondary,
    fontFamily: FONT.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  walletStatusCard: {
    width: '100%',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  walletStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  walletStatusLabel: {
    flex: 1,
    color: COLORS.textSecondary,
    fontFamily: FONT.medium,
    fontSize: 12,
  },
  walletStatusValue: { color: COLORS.text, fontFamily: FONT.semibold, fontSize: 12 },
  walletStatusActions: { flexDirection: 'row', gap: 10, marginTop: 2 },
  inlineActionButton: {
    minHeight: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    backgroundColor: COLORS.surfaceSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  inlineActionText: { color: COLORS.text, fontFamily: FONT.semibold, fontSize: 12 },
  securityCard: {
    width: '100%',
    minHeight: 106,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    backgroundColor: COLORS.surfaceSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  securityIcon: {
    width: 46,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.purple, 0.24),
  },
  securityCopy: { flex: 1, minWidth: 0, gap: 3 },
  securityTitle: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 16, lineHeight: 20 },
  securityBody: {
    color: COLORS.textSecondary,
    fontFamily: FONT.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  securityButton: {
    minHeight: 34,
    borderRadius: 10,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity('#FFFFFF', 0.04),
  },
  securityButtonText: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 12 },
  networkRow: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  networkChip: {
    minHeight: 34,
    borderRadius: RADII.pill,
    justifyContent: 'center',
    paddingHorizontal: 16,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  networkChipActive: { backgroundColor: COLORS.purpleSoft, borderColor: COLORS.purpleSoft },
  networkChipText: { color: COLORS.textSecondary, fontFamily: FONT.bold, fontSize: 12 },
  networkChipTextActive: { color: COLORS.text },
  assetsSection: { width: '100%', gap: 14 },
  sectionHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 22, lineHeight: 27 },
  searchButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  assetFilters: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  filterButton: { minHeight: 36, justifyContent: 'center' },
  filterText: { color: COLORS.textSecondary, fontFamily: FONT.bold, fontSize: 12 },
  filterTextActive: { color: COLORS.purpleSoft },
  filterUnderline: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -1,
    height: 2,
    borderRadius: 999,
    backgroundColor: COLORS.purpleSoft,
  },
  assetList: { width: '100%', gap: 10 },
  assetRow: {
    width: '100%',
    minHeight: 66,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: COLORS.surface,
  },
  assetIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetCopy: { flex: 1, minWidth: 0, gap: 2 },
  assetSymbol: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 16 },
  assetName: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 11 },
  assetValues: { maxWidth: '42%', alignItems: 'flex-end', gap: 2 },
  assetAmount: { color: COLORS.text, fontFamily: FONT.semibold, fontSize: 15 },
  assetUsd: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 10 },
  emptyCard: {
    minHeight: 84,
    borderRadius: 14,
    justifyContent: 'center',
    padding: 14,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 4,
  },
  emptyTitle: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 14 },
  emptyBody: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 12 },
  dappsCard: {
    width: '100%',
    minHeight: 160,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  dappsCopy: { flex: 1, minWidth: 0, padding: 22, gap: 8 },
  dappsTitle: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 20 },
  dappsBody: {
    color: COLORS.textSecondary,
    fontFamily: FONT.medium,
    fontSize: 13,
    lineHeight: 18,
  },
  dappsButton: {
    alignSelf: 'flex-start',
    minHeight: 40,
    borderRadius: 10,
    justifyContent: 'center',
    marginTop: 6,
    paddingHorizontal: 22,
    backgroundColor: COLORS.purpleSoft,
  },
  dappsButtonText: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 14 },
  dappsOrb: { width: 124, alignItems: 'center', justifyContent: 'center', opacity: 0.9 },
  swapOverlay: {
    flex: 1,
    backgroundColor: withOpacity('#000000', 0.72),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  swapModal: {
    width: '100%',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceElevated,
    padding: 20,
    gap: 14,
  },
  swapIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withOpacity(COLORS.web3Blue, 0.12),
    borderWidth: 1,
    borderColor: withOpacity(COLORS.web3Blue, 0.22),
  },
  swapTitle: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 20 },
  swapBody: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 13, lineHeight: 20 },
  swapChecklist: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: withOpacity(COLORS.background, 0.34),
    padding: 12,
    gap: 6,
  },
  swapItem: { color: COLORS.textSecondary, fontFamily: FONT.medium, fontSize: 12 },
  swapButton: {
    minHeight: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purpleSoft,
  },
  swapButtonText: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 14 },
  activitySection: { width: '100%', gap: 14 },
  seeAllText: { color: COLORS.purpleSoft, fontFamily: FONT.bold, fontSize: 13 },
  activityList: { gap: 12 },
  emptyActivityText: {
    color: COLORS.textSecondary,
    fontFamily: FONT.medium,
    fontSize: 12,
    lineHeight: 18,
  },
  activityRow: {
    width: '100%',
    minHeight: 64,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: COLORS.surfaceSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  activityIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityCopy: { flex: 1, minWidth: 0, gap: 2 },
  activityTitle: { color: COLORS.text, fontFamily: FONT.bold, fontSize: 14 },
  activityStatus: { fontFamily: FONT.bold, fontSize: 11 },
  activityValue: {
    maxWidth: '36%',
    color: COLORS.text,
    fontFamily: FONT.medium,
    fontSize: 13,
    textAlign: 'right',
  },
  disabledAction: { opacity: 0.55 },
  pressed: { opacity: 0.72, transform: [{ scale: 0.99 }] },
});
