import type { AstraFeatureFlags } from './astraFlags';

export const ASTRA_REMOTE_CONFIG_ALLOWED_KEYS = [
  'ASTRA_ENABLED',
  'ASTRA_CONTEXT_ENABLED',
  'ASTRA_NOTIFICATIONS_ENABLED',
  'ASTRA_WEB3_SECURITY_ENABLED',
  'ASTRA_VOICE_ENABLED',
  'ASTRA_TOOL_EXECUTION_ENABLED',
  'ASTRA_TOOL_REGISTRY_ENABLED',
  'ASTRA_TOOL_CONFIRMATION_ENABLED',
  'ASTRA_TOOL_AUDIT_ENABLED',
  'ASTRA_TOOL_MOCK_EXECUTION_ENABLED',
  'ASTRA_TOOL_LOCAL_ACTIONS_ENABLED',
  'ASTRA_TOOL_MARK_INBOX_READ_ENABLED',
  'ASTRA_TOOL_DISMISS_INSIGHT_ENABLED',
  'ASTRA_TOOL_SAVE_NOTE_ENABLED',
  'ASTRA_TOOL_SAVE_ORDER_DRAFT_ENABLED',
  'ASTRA_TOOL_PIN_ASSET_ENABLED',
  'ASTRA_TOOL_PIN_INSIGHT_ENABLED',
  'ASTRA_TOOL_MUTE_SURFACE_ENABLED',
  'ASTRA_TOOL_SET_INTENSITY_MODE_ENABLED',
  'ASTRA_TOOL_CONFIRMATION_UI_ENABLED',
  'ASTRA_TOOL_REAL_EXECUTION_ENABLED',
  'ASTRA_RISK_ENGINE_ENABLED',
  'ASTRA_RISK_READ_ONLY_ENABLED',
  'ASTRA_RISK_TOKEN_SCAN_ENABLED',
  'ASTRA_RISK_APPROVAL_SCAN_ENABLED',
  'ASTRA_RISK_EXTERNAL_ADAPTERS_ENABLED',
  'ASTRA_RISK_EVENT_PUBLISHING_ENABLED',
  'ASTRA_RISK_RELEVANCE_ENABLED',
  'ASTRA_RISK_INSIGHT_HOST_ENABLED',
  'ASTRA_RISK_INSIGHT_CARDS_ENABLED',
  'ASTRA_RISK_INSIGHT_BANNERS_ENABLED',
  'ASTRA_RISK_INSIGHT_CRITICAL_ENABLED',
  'ASTRA_RISK_REAL_EXECUTION_ENABLED',
  'ASTRA_QA_HUB_ENABLED',
  'ASTRA_QA_HUB_RISK_SANDBOX_ENABLED',
  'ASTRA_QA_HUB_LOCAL_TOOLS_SANDBOX_ENABLED',
  'ASTRA_QA_HUB_CONFIRMATION_BRIDGE_ENABLED',
  'ASTRA_QA_HUB_REMOTE_CONFIG_PANEL_ENABLED',
  'ASTRA_QA_HUB_UI_SANDBOX_ENABLED',
  'ASTRA_QA_HUB_FLAGS_PANEL_ENABLED',
  'ASTRA_MEMORY_ENABLED',
  'ASTRA_INBOX_ENABLED',
  'ASTRA_UI_MICROCARD_ENABLED',
  'ASTRA_UI_ALERT_BANNER_ENABLED',
  'ASTRA_UI_FLOATING_ORB_ENABLED',
  'ASTRA_UI_INSIGHT_SHEET_ENABLED',
  'ASTRA_UI_CONFIRMATION_SHEET_ENABLED',
  'ASTRA_UI_INBOX_ENABLED',
  'ASTRA_UI_VOICE_PLACEHOLDER_ENABLED',
  'ASTRA_UI_SURFACE_INSIGHTS_ENABLED',
  'ASTRA_UI_SURFACE_MARKET_ENABLED',
  'ASTRA_UI_SURFACE_TRADE_ENABLED',
  'ASTRA_UI_SURFACE_WALLET_ENABLED',
  'ASTRA_UI_SURFACE_PORTFOLIO_ENABLED',
  'ASTRA_MEMORY_LOCAL_ENABLED',
  'ASTRA_MEMORY_DISMISSALS_ENABLED',
  'ASTRA_MEMORY_INBOX_PERSISTENCE_ENABLED',
  'ASTRA_NOTIFICATION_ENGINE_ENABLED',
  'ASTRA_NOTIFICATION_QUEUE_ENABLED',
  'ASTRA_NOTIFICATION_COOLDOWN_ENABLED',
  'ASTRA_REMOTE_CONFIG_ENABLED',
  'ASTRA_KILL_SWITCH',
  'ASTRA_SYNC_READ_ENABLED',
  'ASTRA_SYNC_WRITE_ENABLED',
  'ASTRA_NOTIFICATION_LOCAL_DELIVERY_ENABLED',
  'ASTRA_NOTIFICATION_PUSH_ENABLED',
] as const satisfies readonly (keyof AstraFeatureFlags)[];

export function validateAstraRemoteConfig(raw: unknown): Partial<AstraFeatureFlags> {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return {};
  }

  const candidate = raw as Record<string, unknown>;
  const validated: Partial<AstraFeatureFlags> = {};

  ASTRA_REMOTE_CONFIG_ALLOWED_KEYS.forEach((key) => {
    const value = candidate[key];
    if (typeof value === 'boolean') {
      validated[key] = value;
    }
  });

  return validated;
}

export function applyAstraKillSwitches(flags: AstraFeatureFlags): AstraFeatureFlags {
  if (!flags.ASTRA_KILL_SWITCH) {
    return flags;
  }

  return {
    ...flags,
    ASTRA_ENABLED: false,
    ASTRA_SYNC_READ_ENABLED: false,
    ASTRA_SYNC_WRITE_ENABLED: false,
    ASTRA_NOTIFICATION_ENGINE_ENABLED: false,
    ASTRA_NOTIFICATION_QUEUE_ENABLED: false,
    ASTRA_NOTIFICATION_LOCAL_DELIVERY_ENABLED: false,
    ASTRA_NOTIFICATION_PUSH_ENABLED: false,
  };
}

export function mergeAstraRemoteConfig(
  defaults: AstraFeatureFlags,
  remote: Partial<AstraFeatureFlags>,
): AstraFeatureFlags {
  return applyAstraKillSwitches({
    ...defaults,
    ...remote,
  });
}
